#!/usr/bin/env bash
set -euo pipefail

REPO="https://github.com/bpmiranda3099/student-information-system"
BLUEPRINT_URL="https://dashboard.render.com/blueprint/new?repo=${REPO}"

echo "==> Render setup for Student Information System (sis-api)"
echo "    Repo: ${REPO}"
echo

if command -v render >/dev/null 2>&1; then
  echo "==> Validate render.yaml"
  render blueprints validate ./render.yaml
  echo
else
  echo "Install Render CLI: brew install render"
fi

echo "==> Deploy via Blueprint (recommended)"
echo "    ${BLUEPRINT_URL}"
echo
echo "After the service is created, set these env vars in the Render dashboard:"
echo "  DATABASE_URL              Supabase Postgres connection string"
echo "  SUPABASE_URL              https://uzjpuxulgdpgqrynyxvu.supabase.co"
echo "  SUPABASE_SERVICE_ROLE_KEY your service role key"
echo "  GEMINI_API_KEY            your Gemini API key"
echo "  RESEND_API_KEY            your Resend API key"
echo "  EMAIL_FROM                SIS <onboarding@resend.dev>"
echo "  CORS_ORIGINS              https://your-app.vercel.app"
echo
echo "JWT secrets are auto-generated by the blueprint."
echo
echo "Optional — Render MCP for Cursor:"
echo "  1. Create API key: https://dashboard.render.com/u/settings#api-keys"
echo "  2. export RENDER_API_KEY=rnd_xxxxx"
echo "  3. Add Render MCP in ~/.cursor/mcp.json (see docs/obsidian/Deployment Runbook.md)"
echo "  4. Restart Cursor, then ask: 'Set my Render workspace to ...'"
echo
echo "Optional — CLI auth:"
echo "  render login"
echo "  render whoami -o json"
